wandb: WARNING The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
Traceback (most recent call last):
  File "C:\Users\PAVILION 15-DW001LA\Documents\Tesis\CÃ³digos\RNAs\Red_Conv1D\Red_Conv1D.py", line 84, in <module>
    model.fit(x_trainv, y_trainv,
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\wandb\integration\keras\keras.py", line 174, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\keras\engine\training.py", line 1216, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\util\traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\def_function.py", line 910, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\def_function.py", line 958, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\function.py", line 3157, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\function.py", line 3557, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\function.py", line 3391, in _create_graph_function
    graph_function = ConcreteFunction(
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\function.py", line 1593, in __init__
    self._delayed_rewrite_functions = _DelayedRewriteGradientFunctions(
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\function.py", line 683, in __init__
    self._inference_function = _EagerDefinedFunction(
  File "C:\Users\PAVILION 15-DW001LA\miniconda3\lib\site-packages\tensorflow\python\eager\function.py", line 476, in __init__
    fn = pywrap_tf_session.TF_GraphToFunction_wrapper(
KeyboardInterrupt
Epoch 1/30